import { StyleSheet } from 'react-native';

import { colors, fonts, layout } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.paper },
  shell: { flex: 1 },
  topbar: { minHeight: 74, paddingHorizontal: 20, backgroundColor: colors.ink, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  brand: { color: colors.white, fontFamily: fonts.sans, fontSize: 16, fontWeight: '900', letterSpacing: -0.4 },
  brandAccent: { color: colors.blue },
  unit: { color: '#83848A', fontFamily: fonts.mono, fontSize: 7, fontWeight: '800', letterSpacing: 1, marginTop: 5 },
  close: { width: 38, height: 38, borderWidth: 1, borderColor: '#3D3E43', alignItems: 'center', justifyContent: 'center' },
  workspace: { flex: 1 },
  workspaceWide: { flexDirection: 'row' },
  sidebar: { height: 72, backgroundColor: colors.ink, flexDirection: 'row', paddingHorizontal: 4 },
  sidebarWide: { width: 142, height: '100%', flexDirection: 'column', paddingTop: 18 },
  navItem: { flex: 1, minHeight: 58, alignItems: 'center', justifyContent: 'center', gap: 4, paddingHorizontal: 4 },
  navItemActive: { backgroundColor: colors.blue },
  navText: { color: '#77787D', fontFamily: fonts.sans, fontSize: 7, fontWeight: '900', letterSpacing: 0.35 },
  navTextActive: { color: colors.white },
  content: { flex: 1 },
  contentInner: { width: '100%', maxWidth: layout.maxWidth, alignSelf: 'center', paddingHorizontal: 20, paddingTop: 34, paddingBottom: 60 },
  loader: { marginBottom: 20 },
  notice: { minHeight: 48, paddingHorizontal: 15, backgroundColor: '#DDE6FF', borderLeftWidth: 4, borderLeftColor: colors.blue, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18 },
  noticeText: { color: colors.ink, fontFamily: fonts.sans, fontSize: 11, fontWeight: '700', flex: 1 },
  pageHead: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 16 },
  eyebrow: { color: colors.blue, fontFamily: fonts.mono, fontSize: 8, fontWeight: '900', letterSpacing: 1.4, marginBottom: 10 },
  pageTitle: { color: colors.ink, fontFamily: fonts.sans, fontSize: 35, lineHeight: 37, fontWeight: '800', letterSpacing: -1.8 },
  createButton: { minHeight: 48, paddingHorizontal: 15, backgroundColor: colors.blue, flexDirection: 'row', alignItems: 'center', gap: 9 },
  createText: { color: colors.white, fontFamily: fonts.sans, fontSize: 8, fontWeight: '900', letterSpacing: 0.9 },
  total: { color: colors.muted, fontFamily: fonts.mono, fontSize: 8, fontWeight: '800' },
  toolbar: { minHeight: 70, marginTop: 30, backgroundColor: colors.white, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  segment: { flexDirection: 'row', backgroundColor: colors.soft, padding: 3 },
  segmentItem: { height: 44, minWidth: 70, alignItems: 'center', justifyContent: 'center' },
  segmentActive: { backgroundColor: colors.ink },
  segmentText: { color: colors.muted, fontFamily: fonts.sans, fontSize: 8, fontWeight: '900' },
  segmentTextActive: { color: colors.white },
  dateNav: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 13 },
  dateNavText: { color: colors.ink, fontFamily: fonts.sans, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  summaryGrid: { marginTop: 10, gap: 8 },
  summaryGridWide: { flexDirection: 'row' },
  summary: { flex: 1, minHeight: 96, padding: 17, backgroundColor: colors.white },
  summaryValue: { color: colors.ink, fontFamily: fonts.sans, fontSize: 30, fontWeight: '800', letterSpacing: -1.3 },
  summaryLabel: { color: colors.muted, fontFamily: fonts.mono, fontSize: 7, fontWeight: '800', letterSpacing: 0.8, marginTop: 8 },
  scheduleList: { marginTop: 24, borderTopWidth: 1, borderColor: colors.line },
  appointment: { minHeight: 130, paddingVertical: 17, borderBottomWidth: 1, borderColor: colors.line, flexDirection: 'row', gap: 18 },
  appointmentInactive: { opacity: 0.48 },
  appointmentTime: { width: 80 },
  appointmentTimeText: { color: colors.ink, fontFamily: fonts.sans, fontSize: 25, fontWeight: '800', letterSpacing: -1 },
  appointmentDay: { color: colors.muted, fontFamily: fonts.mono, fontSize: 7, textTransform: 'uppercase', marginTop: 5 },
  appointmentCopy: { flex: 1 },
  appointmentTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  appointmentClient: { color: colors.ink, fontFamily: fonts.sans, fontSize: 16, fontWeight: '800' },
  appointmentStatus: { color: colors.success, fontFamily: fonts.mono, fontSize: 7, fontWeight: '900', letterSpacing: 0.7 },
  appointmentMeta: { color: colors.muted, fontFamily: fonts.sans, fontSize: 10, marginTop: 6 },
  paymentMeta: { color: colors.success, fontFamily: fonts.mono, fontSize: 7, fontWeight: '900', letterSpacing: 0.5, marginTop: 6 },
  appointmentActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 12 },
  paidButton: { minHeight: 44, paddingHorizontal: 9, borderWidth: 1, borderColor: '#A8D5BA', flexDirection: 'row', alignItems: 'center', gap: 5 },
  paidText: { color: colors.success, fontFamily: fonts.sans, fontSize: 7, fontWeight: '900', letterSpacing: 0.5 },
  smallActionButton: { minHeight: 44, paddingHorizontal: 7, alignItems: 'center', justifyContent: 'center' },
  smallAction: { color: colors.ink, fontFamily: fonts.sans, fontSize: 7, fontWeight: '900', letterSpacing: 0.7 },
  smallDanger: { color: colors.danger, fontFamily: fonts.sans, fontSize: 7, fontWeight: '900', letterSpacing: 0.7 },
  empty: { paddingVertical: 50, alignItems: 'center' },
  emptyTitle: { color: colors.ink, fontFamily: fonts.sans, fontSize: 24, fontWeight: '800' },
  emptyText: { color: colors.muted, fontFamily: fonts.sans, fontSize: 11, marginTop: 7 },
  editor: { marginTop: 20, padding: 20, backgroundColor: colors.white, borderTopWidth: 5, borderTopColor: colors.blue },
  editorHead: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 20 },
  cardTitle: { color: colors.ink, fontFamily: fonts.mono, fontSize: 9, fontWeight: '900', letterSpacing: 1.2 },
  cardHint: { color: colors.muted, fontFamily: fonts.sans, fontSize: 10, lineHeight: 15, marginTop: 8 },
  inputLabel: { color: colors.muted, fontFamily: fonts.mono, fontSize: 7, fontWeight: '900', letterSpacing: 0.8, marginBottom: 7, marginTop: 14 },
  chips: { gap: 7, paddingRight: 10 },
  chip: { height: 44, paddingHorizontal: 13, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center' },
  chipActive: { backgroundColor: colors.ink, borderColor: colors.ink },
  chipText: { color: colors.ink, fontFamily: fonts.sans, fontSize: 9, fontWeight: '800' },
  chipTextActive: { color: colors.white },
  inputPair: { flexDirection: 'row', gap: 9 },
  labeledInput: { flex: 1 },
  input: { height: 46, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 12, color: colors.ink, fontFamily: fonts.sans, fontSize: 12 },
  editorSave: { height: 50, marginTop: 20, paddingHorizontal: 16, backgroundColor: colors.blue, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  editorSaveText: { color: colors.white, fontFamily: fonts.sans, fontSize: 8, fontWeight: '900', letterSpacing: 1 },
  searchBox: { height: 54, marginTop: 28, paddingHorizontal: 16, backgroundColor: colors.white, flexDirection: 'row', alignItems: 'center', gap: 11 },
  searchInput: { flex: 1, color: colors.ink, fontFamily: fonts.sans, fontSize: 13 },
  clientList: { marginTop: 22, borderTopWidth: 1, borderColor: colors.line },
  clientRow: { minHeight: 84, borderBottomWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 13 },
  clientAvatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' },
  clientInitial: { color: colors.white, fontFamily: fonts.sans, fontSize: 16, fontWeight: '900' },
  clientCopy: { flex: 1 },
  clientName: { color: colors.ink, fontFamily: fonts.sans, fontSize: 14, fontWeight: '800' },
  clientPhone: { color: colors.muted, fontFamily: fonts.sans, fontSize: 10, marginTop: 4 },
  clientAction: { minHeight: 44, paddingHorizontal: 6, flexDirection: 'row', alignItems: 'center', gap: 7 },
  clientActionText: { color: colors.blue, fontFamily: fonts.sans, fontSize: 7, fontWeight: '900', letterSpacing: 0.8 },
  operationGrid: { marginTop: 28, gap: 10 },
  operationGridWide: { flexDirection: 'row', alignItems: 'flex-start' },
  operationCard: { flex: 1, padding: 20, backgroundColor: colors.white },
  operationButton: { height: 48, marginTop: 18, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' },
  operationButtonText: { color: colors.white, fontFamily: fonts.sans, fontSize: 8, fontWeight: '900', letterSpacing: 1 },
  rule: { minHeight: 51, borderBottomWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  ruleLabel: { color: colors.muted, fontFamily: fonts.sans, fontSize: 10 },
  ruleValue: { color: colors.ink, fontFamily: fonts.sans, fontSize: 10, fontWeight: '800', textAlign: 'right' },
  subheading: { color: colors.ink, fontFamily: fonts.mono, fontSize: 9, fontWeight: '900', letterSpacing: 1.2, marginTop: 38, marginBottom: 12 },
  blockList: { borderTopWidth: 1, borderColor: colors.line },
  blockRow: { minHeight: 76, borderBottomWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 12 },
  blockIcon: { width: 40, height: 40, backgroundColor: '#FBE9E7', alignItems: 'center', justifyContent: 'center' },
  blockCopy: { flex: 1 },
  blockTitle: { color: colors.ink, fontFamily: fonts.sans, fontSize: 12, fontWeight: '800' },
  blockMeta: { color: colors.muted, fontFamily: fonts.sans, fontSize: 9, marginTop: 4 },
  catalogList: { backgroundColor: colors.white, borderTopWidth: 1, borderColor: colors.line },
  catalogRow: { minHeight: 78, paddingHorizontal: 16, borderBottomWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 12 },
  catalogCopy: { flex: 1 },
  catalogName: { color: colors.ink, fontFamily: fonts.sans, fontSize: 14, fontWeight: '800' },
  catalogMeta: { color: colors.muted, fontFamily: fonts.sans, fontSize: 9, lineHeight: 14, marginTop: 4 },
  statusButton: { minWidth: 78, minHeight: 42, backgroundColor: '#E6F4EC', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 },
  statusButtonOff: { backgroundColor: '#EEEDE8' },
  statusButtonText: { color: colors.success, fontFamily: fonts.mono, fontSize: 7, fontWeight: '900', letterSpacing: 0.7 },
  statusButtonTextOff: { color: colors.muted },
  promoLayout: { marginTop: 28, gap: 12 },
  promoLayoutWide: { flexDirection: 'row', alignItems: 'flex-start' },
  promoForm: { flex: 1.1, padding: 20, backgroundColor: colors.white },
  promoHistory: { flex: 0.9, padding: 20, backgroundColor: colors.white },
  messageInput: { minHeight: 110, padding: 13, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, color: colors.ink, fontFamily: fonts.sans, fontSize: 12, lineHeight: 18, textAlignVertical: 'top' },
  promoRow: { paddingVertical: 18, borderBottomWidth: 1, borderColor: colors.line },
  promoTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  promoTitle: { flex: 1, color: colors.ink, fontFamily: fonts.sans, fontSize: 14, fontWeight: '800' },
  promoStatus: { color: colors.blue, fontFamily: fonts.mono, fontSize: 6, fontWeight: '900', letterSpacing: 0.6 },
  promoMessage: { color: colors.muted, fontFamily: fonts.sans, fontSize: 10, lineHeight: 15, marginTop: 8 },
  cancelPromo: { minHeight: 42, alignSelf: 'flex-start', justifyContent: 'center', marginTop: 6 },
  denied: { flex: 1, backgroundColor: colors.paper, alignItems: 'center', justifyContent: 'center', padding: 30 },
  deniedTitle: { color: colors.ink, fontFamily: fonts.sans, fontSize: 29, fontWeight: '800', marginTop: 18 },
  deniedText: { color: colors.muted, fontFamily: fonts.sans, fontSize: 12, lineHeight: 18, textAlign: 'center', maxWidth: 330, marginTop: 8 },
  deniedButton: { height: 48, marginTop: 22, paddingHorizontal: 20, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center' },
  deniedButtonText: { color: colors.white, fontFamily: fonts.sans, fontSize: 8, fontWeight: '900', letterSpacing: 1 },
});
